version: "1"
services:
  - type: web
    name: your-app-name
    runtime: docker
    plan: free
    branch: main
    rootDir: .
    dockerfilePath: ./Dockerfile
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: EXCHANGE_RATE_API_KEY
        sync: false
      - key: ZAKYA_CLIENT_ID
        sync: false
      - key: ZAKYA_CLIENT_SECRET
        sync: false
      - key: ZAKYA_REDIRECT_URI
        value: https://your-app-name.onrender.com
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_SHOP_URL
        value: minaki-online.myshopify.com
      - key: SHOPIFY_API_VERSION
        value: 2025-01
      - key: SHOPIFY_ACCESS_TOKEN
        sync: false
      - key: POSTGRES_URI
        sync: false
      - key: USER
        sync: false
      - key: PASSWORD
        sync: false
      - key: HOST
        sync: false
      - key: PORT
        value: "6543"
      - key: DBNAME
        value: postgres
      - key: POSTGRES_SESSION_POOL_URI
        sync: false
      - key: SR_EMAIL
        sync: false
      - key: SR_PASSWORD
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: env
        value: prod